# Generated by Django 5.2.3 on 2026-03-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Antibiotics', 'Antibiotics'), ('Painkillers', 'Painkillers'), ('Vaccines', 'Vaccines'), ('Antiviral', 'Antiviral'), ('Other', 'Other')], max_length=100)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
