# Generated by Django 5.2.3 on 2026-03-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_on_duty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Reception', 'Reception'), ('Lab', 'Laboratory Staff'), ('Pharmacy', 'Pharmacist'), ('Payments', 'Billing Staff'), ('Nurse', 'Nurse'), ('WardManager', 'Ward Manager'), ('Admin', 'Administrator')], max_length=20, verbose_name='Select Role'),
        ),
    ]
