# Generated by Django 5.2.3 on 2026-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='department',
            field=models.CharField(choices=[('General OPD', 'General OPD'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Maternity', 'Maternity'), ('Orthopedics', 'Orthopedics'), ('Internal Medicine', 'Internal Medicine'), ('Surgery', 'Surgery'), ('Dental', 'Dental'), ('Eye Clinic', 'Eye Clinic'), ('ENT', 'ENT (Ear, Nose, Throat)'), ('Oncology', 'Oncology'), ('Emergency', 'Emergency Room (ER)')], default='General OPD', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting for Doctor'), ('Consulting', 'In Consultation'), ('Lab', 'In Laboratory'), ('Pharmacy', 'In Pharmacy'), ('Admitted', 'Admitted'), ('Billing', 'Waiting for Payment'), ('Discharged', 'Discharged')], default='Waiting', max_length=20),
        ),
    ]
