# Generated by Django 5.2.3 on 2026-03-11 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('General', 'General'), ('ICU', 'ICU'), ('Pediatric', 'Pediatric'), ('Maternity', 'Maternity'), ('Surgical', 'Surgical')], max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'WardManager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_wards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bed', to='patients.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='beds.ward')),
            ],
        ),
    ]
