# Generated by Django 5.2.3 on 2026-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_insurance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(choices=[('None', 'No Insurance / Cash Pay'), ('RSSB-Mutuelle', 'RSSB / Mutuelle (Rwanda)'), ('RSSB-RAMA', 'RSSB / RAMA (Rwanda)'), ('MMI', 'MMI (Rwanda)'), ('Radiant', 'Radiant (Rwanda)'), ('Sanlam', 'Sanlam (Rwanda)'), ('UAP', 'UAP (Rwanda)'), ('Aetna', 'Aetna (International)'), ('Cigna', 'Cigna (International)'), ('Bupa', 'Bupa (International)'), ('Other', 'Other')], default='None', max_length=100),
        ),
    ]
